@endpoint = http://localhost:{{$dotenv PORT}}

## Liste des users
GET {{ endpoint }}/users

### Créer un utilisateur
POST {{ endpoint }}/register
content-type: application/json

{
   "username": "george",
   "email": "lucasgeorge@gmail.com",
   "password": "THX1138_forever!"
}