@endpoint = http://localhost:{{$dotenv PORT}}

### Create a new profile
POST {{ endpoint }}/register
content-type: application/json

{
   "username": "John",
   "email": "johndoe@gmail.com",
   "password": "Xxxxx!0"
}

### Login Attempt With Correct User
POST {{endpoint}}/login
content-type: application/json

{
   "username": "John" ,
   "password": "Xxxxx!0"
}

### Access attempt profile page
GET {{endpoint}}/profile/1
content-type: application/json

{
   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTI4NTYzNSwiZXhwIjoxNjU1MjkyODM1fQ.4JbCdPchF16W5VkWeT6aW42h38AJAupdO6CfnqAMIEc"
}
