@endpoint = http://localhost:{{$dotenv PORT}}/api

## Users list
GET {{ endpoint }}/users

### Create a new profile
POST {{ endpoint }}/register
content-type: application/json

{
   "username": "amber",
   "email": "lucasgeorge@gmail.com",
   "password": "THX1138_forever!"
}

### Get a profile
GET {{ endpoint }}/users/1

### Delete pablo profile
DELETE {{ endpoint }}/users/5


### Update username an existing profile username
PATCH {{ endpoint }}/users/2
content-type: application/json

{
   "username": "amber"
}

### Create a new profile
POST {{ endpoint }}/register
content-type: application/json

{
   "username": "jack",
   "email": "jacksparrow@gmail.com",
   "password": "THX1138_forever!"
}

### Login Attempt With Correct User
POST {{endpoint}}/login
content-type: application/json

{
   "username": "george" ,
   "password": "THX1138_forever!"
}

### Login Attempt With Incorrect User
POST {{endpoint}}/login
content-type: application/json

{
   "username": "george" ,
   "password": "Ceciestuntest"
}

### Login Attempt Without Password
POST {{endpoint}}/login
content-type: application/json

{
   "username": "george"
}