@endpoint = http://localhost:{{$dotenv PORT}}

### period
POST {{ endpoint }}/game/1
content-type: application/json

{
   "parentType": "game",
   "cardType": "period",
   "text": "text period",
   "tone": true,
   "parentId": 1,
   "previous_card_position": 0
}

### event 27, 20
POST {{ endpoint }}/game/1
content-type: application/json

{
   "parentType": "period",
   "cardType": "event",
   "text": "text event",
   "tone": true,
   "parentId": 20,
   "previous_card_position": 0
}

### scene
POST {{ endpoint }}/game/1
content-type: application/json

{
   "parentType": "event",
   "cardType": "scene",
   "text": "text scene",
   "tone": true,
   "parentId": 2,
   "previous_card_position": 0
}