@endpoint = http://localhost:{{$dotenv PORT}}

### period
POST {{ endpoint }}/game/15
content-type: application/json

{
   "parentType": "game",
   "cardType": "period",
   "text": "text",
   "tone": true,
   "parentId": 13,
   "previous_card_position": 0
}

### event
POST {{ endpoint }}/game/15
content-type: application/json

{
   "parentType": "period",
   "cardType": "event",
   "text": "text event",
   "tone": false,
   "parentId": 54,
   "previous_card_position": 0
}

### scene
POST {{ endpoint }}/game/15
content-type: application/json

{
   "parentType": "event",
   "cardType": "scene",
   "text": "text scene",
   "tone": false,
   "parentId": 8,
   "previous_card_position": 2
}