@endpoint = http://localhost:{{$dotenv PORT}}

### Create a new profile
POST {{ endpoint }}/register
content-type: application/json

{
   "username": "jeremy",
   "email": "jeremy@gmail.com",
   "password": "motdepassedeJérémy?"
}

### Create a new profile
POST {{ endpoint }}/register
content-type: application/json

{
   "username": "adlen",
   "email": "adlen@gmail.com",
   "password": "motdepassedeAdlen?"
}

### Create a new profile
POST {{ endpoint }}/register
content-type: application/json

{
   "username": "victor",
   "email": "victor@gmail.com",
   "password": "motdepassedeVictor?"
}

### Create a new profile
POST {{ endpoint }}/register
content-type: application/json

{
   "username": "pablo",
   "email": "pablo@gmail.com",
   "password": "motdepassedePablo?"
}