@endpoint = http://localhost:{{$dotenv PORT}}

### period
POST {{ endpoint }}/game/15
content-type: application/json

{
   "cardType": "period",
   "text": "text",
   "tone": true,
   "game_id": 13,
   "previous_card_position": 0
}

### event
POST {{ endpoint }}/game/15
content-type: application/json

{
   "card_type": "event",
   "text": "text",
   "tone": true,
   "position": 1,
   "period_id": 1,
   "previous_card_position": 0
}