@endpoint = http://localhost:{{$dotenv PORT}}

### Create a new game with the creator
POST {{ endpoint }}/createNewGame
content-type: application/json

{
   "creator_id": "4"
}

### Access a game with its id
GET {{ endpoint }}/game/2
content-type: application/json

### Deploy game
PATCH {{ endpoint }}/game/2/starting
content-type: application/json

{
   "game":{
      "big_picture": "L'humanité quitte la terre et colonise une autre planète",
      "state": "ongoing",
      "bookend_start": "L'humanité quitte la terre à bord d'un vaisseau, en direction de Mars",
      "bookend_start_tone": "0",
      "bookend_end": "L'humanité échoue dans sa colonisation",
      "bookend_end_tone": "0",
      "creator_id": "4",
      "current_user_id": "4"
   },

   "players": {
      "player_id_1": "4",
      "player_id_2": "2",
      "player_id_3": "3",
      "player_id_4": "1"
   },

   "palette": {
      "paletteCard_1": {
         "text": "Magie",
         "status": "1"
      },
      "paletteCard_2": {
         "text": "L'humanité répéte ses erreurs",
         "status": "1"
      },
      "paletteCard_3": {
         "text": "Requin",
         "status": "0"
      },
      "paletteCard_4": {
         "text": "Voyage dans le temps",
         "status": "0"
      }
   }
}

### Deploy game OLD
PATCH {{ endpoint }}/game/2
content-type: application/json

{
   "game":{
      "big_picture": "Un aventure surnaturelle à travers les étoiles",
      "state": "En cours",
      "bookend_start": "Un vaisseau diplomatique est abordé par l'armée du despote",
      "bookend_start_tone": "0",
      "bookend_end": "L'empire est vaincu",
      "bookend_end_tone": "1",
      "creator_id": "1",
      "current_user_id": "1"
   },

   "players": {
      "player_id_1": "1",
      "player_id_2": "2",
      "player_id_3": "3"
   },

   "palette": {
      "paletteCard_1": {
         "text": "Magie",
         "status": "1"
      },
      "paletteCard_2": {
         "text": "Le Bien contre le Mal",
         "status": "1"
      },
      "paletteCard_3": {
         "text": "Violence trop graphique",
         "status": "0"
      },
      "paletteCard_4": {
         "text": "Voyage dans le temps",
         "status": "0"
      },
      "paletteCard_5": {
         "text": "l'Elu",
         "status": "1"
      }
   }
}